Minor develop/get-started-with-ton.mdx refactoring
ton-community/ton-docs pull request #389
Opened 2023-10-27 13:31 UTC by arynyklas

Minor develop/get-started-with-ton.mdx refactoring

## Why is it important?
To better understanding

2023-10-27 15:04 UTC, SsNiPeR1 requested changes
Line 159: grammar issue: you'll require access to THESE three essential tools.

2023-10-27 15:10 UTC, SsNiPeR1 requested changes

2023-10-27 15:10 UTC, SsNiPeR1 commented on docs/develop/get-started-with-ton.mdx
> +To set up a local development environment, you'll require access to this three essential tools:
s/this/these

2023-10-27 15:13 UTC, SsNiPeR1 approved these changes
All good now.

2023-10-27 15:15 UTC, SsNiPeR1 commented
@reveloper

2023-10-29 05:16 UTC, arynyklas commented
@reveloper

2023-10-30 01:04 UTC, reveloper commented
@arynyklas, @SsNiPeR1, Thank you!

2023-10-30 01:05 UTC, merged